
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    DefaultTableModel table = new DefaultTableModel();
    Vector<Empleado> empleados = new Vector<>();
    
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        table.addColumn("NOMBRE");
        table.addColumn("APELLIDO");
        table.addColumn("GENERO");
        table.addColumn("FECHA NAC.");
        table.addColumn("FECHA ING.");
        table.addColumn("SALARIO");
        jTDatosEmpleados.setModel(table);
    }
    
    public String[] generateRowEmp(Empleado emp) {
        String[] newRow = new String[6];
        newRow[0] = emp.getNombre();
        newRow[1] = emp.getApellido();
        newRow[2] = emp.getGenero();
        newRow[3] = emp.getFechaNac();
        newRow[4] = emp.getFechaIng();
        newRow[5] = Double.toString(emp.getSalario());
        return newRow;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNombre = new javax.swing.JLabel();
        jLApellido = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jTApellido = new javax.swing.JTextField();
        jBIngreso = new javax.swing.JButton();
        jLGenero = new javax.swing.JLabel();
        jLFechaNac = new javax.swing.JLabel();
        jLFechaIng = new javax.swing.JLabel();
        jLSalario = new javax.swing.JLabel();
        jTGenero = new javax.swing.JTextField();
        jTFechaNac = new javax.swing.JTextField();
        jTFechaIng = new javax.swing.JTextField();
        jTSalario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDatosEmpleados = new javax.swing.JTable();
        jBMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLNombre.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(0, 102, 51));
        jLNombre.setText("Introduzca nombre:");

        jLApellido.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLApellido.setForeground(new java.awt.Color(0, 102, 51));
        jLApellido.setText("Introduzca apellido:");

        jTNombre.setBackground(new java.awt.Color(204, 255, 204));
        jTNombre.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jTNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNombreActionPerformed(evt);
            }
        });

        jTApellido.setBackground(new java.awt.Color(204, 255, 204));
        jTApellido.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N

        jBIngreso.setBackground(new java.awt.Color(0, 0, 153));
        jBIngreso.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jBIngreso.setForeground(new java.awt.Color(255, 255, 255));
        jBIngreso.setText("Registrar Empleado");
        jBIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIngresoActionPerformed(evt);
            }
        });

        jLGenero.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLGenero.setForeground(new java.awt.Color(0, 102, 51));
        jLGenero.setText("Introduzca genero:");

        jLFechaNac.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLFechaNac.setForeground(new java.awt.Color(0, 102, 51));
        jLFechaNac.setText("Introduzca fecha de nacimiento:");

        jLFechaIng.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLFechaIng.setForeground(new java.awt.Color(0, 102, 51));
        jLFechaIng.setText("Introduzca fecha de ingreso:");

        jLSalario.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLSalario.setForeground(new java.awt.Color(0, 102, 51));
        jLSalario.setText("Introduzca salario:");

        jTGenero.setBackground(new java.awt.Color(204, 255, 204));
        jTGenero.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N

        jTFechaNac.setBackground(new java.awt.Color(204, 255, 204));
        jTFechaNac.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N

        jTFechaIng.setBackground(new java.awt.Color(204, 255, 204));
        jTFechaIng.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N

        jTSalario.setBackground(new java.awt.Color(204, 255, 204));
        jTSalario.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N

        jTDatosEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTDatosEmpleados);

        jBMostrar.setBackground(new java.awt.Color(255, 51, 51));
        jBMostrar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jBMostrar.setForeground(new java.awt.Color(255, 255, 255));
        jBMostrar.setText("Mostrar Empleados");
        jBMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLNombre)
                                    .addComponent(jLApellido))
                                .addGap(126, 126, 126))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLGenero)
                                    .addComponent(jLFechaNac)
                                    .addComponent(jLFechaIng)
                                    .addComponent(jLSalario))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFechaIng, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLNombre)
                            .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLApellido)
                            .addComponent(jTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLGenero)
                            .addComponent(jTGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLFechaNac)
                            .addComponent(jTFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLFechaIng)
                            .addComponent(jTFechaIng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLSalario)
                            .addComponent(jTSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNombreActionPerformed

    private void jBIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIngresoActionPerformed
        String name = jTNombre.getText();
        String lastName = jTApellido.getText();
        String genere = jTGenero.getText();
        String birth = jTFechaNac.getText();
        String inp = jTFechaIng.getText();
        Double salary = Double.parseDouble(jTSalario.getText());
        
        Empleado emp = new Empleado(
                name,
                lastName,
                genere,
                birth,
                inp,
                salary
        );
        
        empleados.add(emp);
        
        jTNombre.setText("");
        jTApellido.setText("");
        jTGenero.setText("");
        jTFechaNac.setText("");
        jTFechaIng.setText("");
        jTSalario.setText("");
    }//GEN-LAST:event_jBIngresoActionPerformed

    private void jBMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMostrarActionPerformed
        for(int i = 0; i < empleados.size(); i++) {
            table.addRow(generateRowEmp(empleados.elementAt(i)));
        }
    }//GEN-LAST:event_jBMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBIngreso;
    private javax.swing.JButton jBMostrar;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLFechaIng;
    private javax.swing.JLabel jLFechaNac;
    private javax.swing.JLabel jLGenero;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLSalario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JTable jTDatosEmpleados;
    private javax.swing.JTextField jTFechaIng;
    private javax.swing.JTextField jTFechaNac;
    private javax.swing.JTextField jTGenero;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTSalario;
    // End of variables declaration//GEN-END:variables
}


